name: Run Python Tests
description: 'Run Python Tests'

inputs:
  package_name:
    description: 'Package name for coverage'
    required: true
  HTTP_SHELL__AUTH_KEY:
    description: 'HTTP_SHELL__AUTH_KEY'
    required: true


runs:
    using: 'composite'
    steps:
      - name: Run pytest (with coverage) - Unit Tests
        shell: bash
        run: |
          coverage run --source=${{ inputs.package_name }} -m pytest -v -s --durations=0 --ignore=tests_* tests/unit
        env:
          COVERAGE_FILE        : .coverage.unit
          HTTP_SHELL__AUTH_KEY : ${{ inputs.HTTP_SHELL__AUTH_KEY  }}